# Generated by Django 4.0.4 on 2022-05-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_native_city_user_native_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
    ]
